export const GET_POKEDEX_REQUEST = 'GET_POKEDEX_REQUEST';
export const GET_POKEDEX_SUCCESS = 'GET_POKEDEX_SUCCESS';
export const GET_POKEDEX_ERROR = 'GET_POKEDEX_ERROR';

export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_ERROR = 'GET_POKEMON_ERROR';

export const GET_POKEMONSPECIES_REQUEST = 'GET_POKEMONSPECIES_REQUEST';
export const GET_POKEMONSPECIES_SUCCESS = 'GET_POKEMONSPECIES_SUCCESS';
export const GET_POKEMONSPECIES_ERROR = 'GET_POKEMONSPECIES_ERROR';

export const GET_EVOLUTION_CHAIN_REQUEST = 'GET_EVOLUTION_CHAIN_REQUEST';
export const GET_EVOLUTION_CHAIN_SUCCESS = 'GET_EVOLUTION_CHAIN_SUCCESS';
export const GET_EVOLUTION_CHAIN_ERROR = 'GET_EVOLUTION_CHAIN_ERROR';

export const SELECT_POKEDEX = 'SELECT_POKEDEX';
export const FILTER_POKEDEX = 'FILTER_POKEDEX';
