// Constants to resolve image filenames with pokemondb api

export const forms = {
  '29': ['nidoran-f'],
  '32': ['nidoran-m'],
  '382': ['kyogre', 'kyogre-primal'],
  '383': ['groudon', 'groudon-primal'],
  '386': ['deoxys-normal', 'deoxys-attack', 'deoxys-defense', 'deoxys-speed'],
  '413': ['wormadam-plant', 'wormadam-sandy', 'wormadam-trash'],
  '479': [
    'rotom-normal',
    'rotom-heat',
    'rotom-wash',
    'rotom-frost',
    'rotom-fam',
    'rotom-mow',
  ],
  '487': ['giratina-altered', 'giratina-origin'],
  '492': ['shaymin-land', 'shaymin-sky'],
  '555': ['darmanitan-standard', 'darmanitan-zen'],
  '641': ['tornadus-incarnate', 'tornadus-therian'],
  '642': ['thundurus-incarnate', 'thundurus-therian'],
  '645': ['landorus-incarnate', 'landorus-therian'],
  '646': ['kyurem-normal', 'kyurem-black', 'kyurem-white'],
  '647': ['keldeo', 'keldeo-resolute'],
  '648': ['meloetta-aria', 'meloetta-pirouette'],
  '658': ['greninja', 'greninja-ash'],
  '678': ['meowstic-male', 'meowstic-female'],
  '681': ['aegislash-blade', 'aegislash-shield'],
  '710': ['pumpkaboo-super'],
  '711': ['gourgeist-super'],
  '718': ['zygarde-50', 'zygarde-10', 'zygarde-complete'],
  '720': ['hoopa-confined', 'hoopa-unbound'],
  '745': ['lycanroc-midday', 'lycanroc-midnight', 'lycanroc-dusk'],
  '741': [
    'oricorio-baile',
    'oricorio-pom-pom',
    'oricorio-pau',
    'oricorio-sensu',
  ],
  '746': ['wishiwashi-solo', 'wishiwashi-school'],
  '774': ['minior-meteor', 'minior-core'],
  '800': [
    'necrozma',
    'necrozma-dusk-mane',
    'necrozma-dawn-wings',
    'necrozma-ultra',
  ],
};

export const alola = {
  '19': ['rattata', 'rattata-alolan'],
  '20': ['raticate', 'raticate-alolan'],
  '26': ['raichu', 'raichu-alolan'],
  '27': ['sandshrew', 'sandshrew-alolan'],
  '28': ['sandslash', 'sandslash-alolan'],
  '37': ['vulpix', 'vulpix-alolan'],
  '38': ['ninetales', 'ninetales-alolan'],
  '50': ['diglett', 'diglett-alolan'],
  '51': ['dugtrio', 'dugtrio-alolan'],
  '52': ['meowth', 'meowth-alolan'],
  '53': ['persian', 'persian-alolan'],
  '74': ['geodude', 'geodude-alolan'],
  '75': ['graveler', 'graveler-alolan'],
  '76': ['golem', 'golem-alolan'],
  '88': ['grimer', 'grimer-alolan'],
  '89': ['muk', 'muk-alolan'],
  '103': ['exeggutor', 'exeggutor-alolan'],
  '105': ['marowak', 'marowak-alolan'],
};

export const megaevolutions = {
  '3': ['venusaur', 'venusaur-mega'],
  '6': ['charizard', 'charizard-mega-x', 'charizard-mega-y'],
  '9': ['blastoise', 'blastoise-mega'],
  '15': ['beedrill', 'beedrill-mega'],
  '18': ['pidgeot', 'pidgeot-mega'],
  '65': ['alakazam', 'alakazam-mega'],
  '80': ['slowbro', 'slowbro-mega'],
  '94': ['gengar', 'gengar-mega'],
  '115': ['kangaskhan', 'kangaskhan-mega'],
  '127': ['pinsir', 'pinsir-mega'],
  '130': ['gyarados', 'gyarados-mega'],
  '142': ['aerodactyl', 'aerodactyl-mega'],
  '150': ['mewtwo', 'mewtwo-mega-x', 'mewtwo-mega-y'],
  '181': ['ampharos', 'ampharos-mega'],
  '208': ['steelix', 'steelix-mega'],
  '212': ['scizor', 'scizor-mega'],
  '214': ['heracross', 'heracross-mega'],
  '229': ['houndoom', 'houndoom-mega'],
  '248': ['tyranitar', 'tyranitar-mega'],
  '254': ['sceptile', 'sceptile-mega'],
  '257': ['blaziken', 'blaziken-mega'],
  '260': ['swampert', 'swampert-mega'],
  '282': ['gardevoir', 'gardevoir-mega'],
  '302': ['sableye', 'sableye-mega'],
  '303': ['mawile', 'mawile-mega'],
  '306': ['aggron', 'aggron-mega'],
  '308': ['medicham', 'medicham-mega'],
  '310': ['manectric', 'manectric-mega'],
  '319': ['sharpedo', 'sharpedo-mega'],
  '323': ['camerupt', 'camerupt-mega'],
  '334': ['altaria', 'altaria-mega'],
  '354': ['banette', 'banette-mega'],
  '359': ['absol', 'absol-mega'],
  '362': ['glalie', 'glalie-mega'],
  '373': ['salamence', 'salamence-mega'],
  '376': ['metagross', 'metagross-mega'],
  '380': ['latias', 'latias-mega'],
  '381': ['latios', 'latios-mega'],
  '384': ['rayquaza', 'rayquaza-mega'],
  '428': ['lopunny', 'lopunny-mega'],
  '475': ['gallade', 'gallade-mega'],
  '445': ['garchomp', 'garchomp-mega'],
  '448': ['lucario', 'lucario-mega'],
  '460': ['abomasnow', 'abomasnow-mega'],
  '531': ['audino', 'audino-mega'],
  '719': ['diancie', 'diancie-mega'],
};
